Use the following code for the questions below:

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

1. How many negative numbers are there?

In [2]:
import numpy as np

In [3]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [7]:
neg_num = a[a < 0]

In [8]:
len(neg_num)

4

2. How many positive numbers are there?

In [5]:
pos_num = a[a > 0]

In [6]:
len(pos_num)

5

3. How many even positive numbers are there?

In [9]:
even_pos_num = pos_num[pos_num % 2 == 0]

In [10]:
len(even_pos_num)

3

4. If you were to add 3 to each data point, how many positive numbers would there be?

In [11]:
add_three = a + 3

In [12]:
new_pos_num = add_three[add_three > 0]

In [13]:
len(new_pos_num)

10

5. If you squared each number, what would the new mean and standard deviation be?

In [14]:
a_squared = a ** 2

In [15]:
a_squared.mean()

74.0

In [17]:
a_squared.std()

144.0243035046516

6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering: https://www.theanalysisfactor.com/centering-and-standardizing-predictors/

In [19]:
centered_a = a - a.mean()

In [20]:
centered_a.mean()

0.0

7. Calculate the z-score for each data point. Recall that the z-score is given by:

            Z=(x−μ)/σ


In [21]:
z_score = (a - a.mean()) / a.std() 

In [24]:
z_score

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.
- Use python's built in functionality/operators to determine the following:    

## a

In [1]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

- Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [5]:
sum_of_a = sum(a)

sum_of_a

- Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [3]:
min_of_a = min(a)

In [4]:
min_of_a

1

- Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list


In [7]:
max_of_a = max(a)

In [8]:
max_of_a

10

- Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list


In [9]:
mean_of_a = sum(a) / len(a)

In [10]:
mean_of_a

5.5

- Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [11]:
product_of_a = [i ** 2 for i in a]

In [12]:
product_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

- Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]


In [14]:
squares_of_a = [i ** 2 for i in a]

In [15]:
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

- Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [18]:
odds_in_a = [i for i in a if i % 2 == 1]

In [19]:
odds_in_a

[1, 3, 5, 7, 9]

- Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [20]:
evens_in_a = [i for i in a if i % 2 == 0]

In [21]:
evens_in_a

[2, 4, 6, 8, 10]

## b

What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...


- Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
            b = [
                [3, 4, 5],
                [6, 7, 8]
            ]

In [5]:
b = [
          [3, 4, 5],
          [6, 7, 8]
      ]

- Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
            sum_of_b = 0
            for row in b:
                sum_of_b += sum(row)

In [6]:
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

In [7]:
b = np.array(b)

In [8]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [9]:
sum_of_b = b.sum()

In [10]:
sum_of_b

33

- Exercise 2 - refactor the following to use numpy. 
        min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [11]:
min_of_b = b.min()

In [12]:
min_of_b

3

- Exercise 3 - refactor the following maximum calculation to find the answer with numpy. 
        
        max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [13]:
max_of_b = b.max()

max_of_b

- Exercise 4 - refactor the following using numpy to find the mean of b

        mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [14]:
mean_of_b = b.mean()

In [15]:
mean_of_b

5.5

- Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

        product_of_b = 1
        for row in b:
            for number in row:
                product_of_b *= number

In [16]:
product_of_b = b.prod()

In [17]:
product_of_b

20160

- Exercise 6 - refactor the following to use numpy to find the list of squares 

        squares_of_b = []
        for row in b:
            for number in row:
                squares_of_b.append(number**2)

In [18]:
squares_of_b = np.power(b,2)

In [19]:
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

- Exercise 7 - refactor using numpy to determine the odds_in_b

        odds_in_b = []
        for row in b:
            for number in row:
                if(number % 2 != 0):
                    odds_in_b.append(number)


In [20]:
odds_in_b = b[b % 2 != 0]

In [21]:
odds_in_b

array([3, 5, 7])

- Exercise 8 - refactor the following to use numpy to filter only the even numbers

        evens_in_b = []
        for row in b:
            for number in row:
                if(number % 2 == 0):
                    evens_in_b.append(number)

In [22]:
evens_in_b = b[b % 2 == 0]

In [23]:
evens_in_b

array([4, 6, 8])

- Exercise 9 - print out the shape of the array b.

In [24]:
b.shape

(2, 3)

- Exercise 10 - transpose the array b.

In [25]:
b.T

array([[3, 6],
       [4, 7],
       [5, 8]])

- Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)


In [26]:
b.reshape(6)

array([3, 4, 5, 6, 7, 8])

- Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [27]:
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

## c

- Setup 3

        c = [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]
        ]

* HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

In [28]:
c = [
      [1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]
  ]

In [29]:
c = np.array(c)

In [30]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- Exercise 1 - Find the min, max, sum, and product of c.

In [31]:
c.min(), c.max(), c.sum(), c.prod()

(1, 9, 45, 362880)

- Exercise 2 - Determine the standard deviation of c.

In [33]:
c.std()

2.581988897471611

- Exercise 3 - Determine the variance of c.

In [34]:
c.var()

6.666666666666667

- Exercise 4 - Print out the shape of the array c

In [36]:
c.shape

(3, 3)

- Exercise 5 - Transpose c and print out transposed result.

In [37]:
c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

- Exercise 6 - Get the dot product of the array c with c. 

In [44]:
np.dot(c, c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

- Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [43]:
(c * c.T).sum()

261

- Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [46]:
(c * c.T).prod()

131681894400

- Setup 4

        d = [
            [90, 30, 45, 0, 120, 180],
            [45, -90, -30, 270, 90, 0],
            [60, 45, -45, 90, -45, 180]
        ]

In [47]:
 d = [
      [90, 30, 45, 0, 120, 180],
      [45, -90, -30, 270, 90, 0],
      [60, 45, -45, 90, -45, 180]
  ]

In [48]:
d = np.array(d)

In [49]:
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

- Exercise 1 - Find the sine of all the numbers in d

In [50]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

- Exercise 2 - Find the cosine of all the numbers in d

In [51]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

- Exercise 3 - Find the tangent of all the numbers in d

In [52]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

- Exercise 4 - Find all the negative numbers in d

In [53]:
d[d < 0]

array([-90, -30, -45, -45])

- Exercise 5 - Find all the positive numbers in d

In [54]:
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

- Exercise 6 - Return an array of only the unique numbers in d.


In [55]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

- Exercise 7 - Determine how many unique numbers there are in d.

In [56]:
len(np.unique(d))

11

- Exercise 8 - Print out the shape of d.

In [57]:
d.shape

(3, 6)

- Exercise 9 - Transpose and then print out the shape of d.


In [58]:
d.T.shape

(6, 3)

- Exercise 10 - Reshape d into an array of 9 x 2

In [59]:
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])

Awesome Bonus For much more practice with numpy, Go to https://github.com/rougier/numpy-100 and clone the repo down to your laptop. Next, go to https://github.com/new to make a new repo. Name it numpy-100, and follow the directions to "push an existing repository from the command line" so that you can push up your changes to your own account.